### ISSUE TITLE
move to netstandard2.0

### ISSUE THREAD

**Issue by antontuz** [nokitakaze/pedersen-hash.net#1]
in my opinion netstandard is common version so if you wanna sharing library as nupkg you shouldn't avoid my recommendation - "move to netstandard2.0"

**Comment by antontuz** [comment]
> Package PedersenHashNet 0.1.2 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). 
> Package PedersenHashNet 0.1.2 supports: netcoreapp3.1 (.NETCoreApp,Version=v3.1)

**Comment by antontuz** [comment]
you can do the same:
https://github.com/somdoron/NaCl.net/blob/aee0c42faf09e7c4f4eea66a395aa77b2c30ce6d/NaCl.net/NaCl.net.csproj#L8

**Comment by nokitakaze** [comment]
Moved to .Net Standard 2.1

2.0 not available due to incompatibility
